[FEAT] Group Refact + 고도화
swsnu/swppfall2022-team4 pull request #70
Opened 2022-11-14 08:52 UTC by blackruby02

- [ ] - refactoring
- [ ] - testing 올리기
- [ ] - 검색기능
- [ ] - 최대인원 백엔드 구현
- [ ] - 최대인원 프론트엔드 구현
- [ ] - 기간 순서대로 백엔드
- [ ] - 기간 순서대로 프론트
- [ ] - 그룹장 위임 기능 만들기

2022-11-23 07:11 UTC, blackruby02 commented
group 인증에서 날짜 불러오는 부분이(달력 클릭하면 날짜 select 되는 부분) front 페이지만 뺐습니다. 지형님 마지막 버전걸 다시 가져오든 하면 될 것 같습니다. 나머지는 모두 되었습니다. 이 버전 pr 하고 해당 부분만 따로 파서 다시 pr 하겠습니다.
front testing에서 지도 부분은 kakao를 mock 하려고 했으나 잘 안되어서 버리고 나머지 부분은 빠짐 없이 짰습니다. 카카오 맵 비중이 있는 페이지는 나머지를 다 짜도 80%가 안 넘어서 논의해보면 좋을 듯합니다.

2022-11-23 08:37 UTC, KJYoung requested changes
frontend/public/index.html의 appkey를 env 파일에 담도록 할 수 있으신가요? html파일이라 어떻게 env로 하나 싶긴 하네요..?

2022-11-23 14:34 UTC, KJYoung commented
+ Map에서 Key 관련 수정에 대해서 아까 실습 끝나고 이야기 했었습니다.

2022-11-23 15:00 UTC, blackruby02 commented
map 은 수정했는데 key는 잘 안되네요(key가 src로 안들어감) #78에 써놨는데 이번주 말이나 다음주에 한번더 해보겠습니다.

2022-11-23 15:03 UTC, KJYoung commented
잠깐 찾아봤는데 https://theubermensch.tistory.com/229 를 참고하시면 도움이 될 것 같습니다.

2022-11-23 15:32 UTC, blackruby02 commented
오.. 저걸 힌트로 요리조리 하니 되었습니다. 감사합니다!

2022-11-23 16:37 UTC, KJYoung commented
Code smell 관련해서 보고 있는데, 최대 인원이 2이상일 것을 강제할 필요가 있을까요?
1인 그룹도 생성할 여지를 두는 것도 큰 문제는 없을 것 같습니다.
다른분들은 어떻게 생각하시나요? @seuha516 @jihyungKo

2022-11-23 16:40 UTC, KJYoung requested changes

2022-11-23 16:40 UTC, KJYoung commented on frontend/src/containers/group/GroupCreate.tsx
> +        for (let i = 0; i < data.length; i++) {
https://sonarcloud.io/project/issues?pullRequest=70&issues=AYSJ5IBWIim1EWDt8ARI&open=AYSJ5IBWIim1EWDt8ARI&id=swsnu_swppfall2022-team4

(frontend/src/containers/group/GroupCreate.tsx 194Line) 은 sonalcloud 추천대로 for - of loop로 바꾸는게 더 깔끔할 것 같습니다.

2022-11-23 16:40 UTC, KJYoung commented on frontend/src/containers/group/GroupList.tsx
> +      for (let i = 0; i < result.length; i++) {
마찬가지로 for of loop으로 바꾸는게 나을 것 같습니다.

2022-11-23 16:46 UTC, KJYoung approved these changes

2022-11-23 19:25 UTC, jihyungKo commented
> Code smell 관련해서 보고 있는데, 최대 인원이 2이상일 것을 강제할 필요가 있을까요? 1인 그룹도 생성할 여지를 두는 것도 큰 문제는 없을 것 같습니다. 다른분들은 어떻게 생각하시나요? @seuha516 @jihyungKo

sonarcloud에서 삼항연산자같이 일부 기능 자체를 code smell로 간주하는 경우도 있어서 저는 강제하지 않아도 좋을 것 같습니다!

2022-11-24 01:50 UTC, KJYoung commented
- [ ] 1인 그룹 가능하게
- [ ] env 파일 노션 및 env.tar.enc로 업데이트

2022-11-24 01:53 UTC, KJYoung commented
Notion에 frontend env 업데이트는 제가 해뒀습니다.
merge된 이후에 @seuha516 님이 develop branch에서 env.tar.enc 파일 업데이트 해주시겠어요?

2022-11-24 02:00 UTC, seuha516 commented
@KJYoung 넵 merge 전부 되면 한꺼번에 정리해서 push 하겠습니다

2022-11-24 02:12 UTC, KJYoung commented
Merge해도 될 것 같습니다 수고하셨어요!

2022-11-24 02:27 UTC, merged